analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.28834
title: FRANCISCO CUBIDES
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.9375
  brandStrength: 0.625
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d4d4d4'
    - '#2b2b2b'
    - '#919191'
  lightness: 0.5
purpose: []
favicon: null
name: FranciscoCubides
typography_spectrum: 0.60121
