name: FranciscoCubides
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60121
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d4d4d4'
    - '#2b2b2b'
    - '#919191'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
