name: FranciscoCubides
favicon: null
layout_spectrum: 0.28834
typography_spectrum: 0.60121
title: TEST DE CONSTRUCCION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d4d4d4'
    - '#2b2b2b'
    - '#919191'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
